tabbed_layout:
  tab_list: ['parts0', 'parts1', 'parts2', 'parts3', 'parts4']
  parts0:
    name: 'parts(act)'
    type: push
    yaml_file: 'package://robot_assembler/config/kxr_parts00_button_layout.yaml'
  parts1:
    name: 'parts(sub)'
    type: push
    yaml_file: 'package://robot_assembler/config/kxr_parts01_button_layout.yaml'
  parts2:
    name: 'parts(body)'
    type: push
    yaml_file: 'package://robot_assembler/config/kxr_parts02_button_layout.yaml'
  parts3:
    name: 'parts(sensor)'
    type: push
    yaml_file: 'package://robot_assembler/config/kxr_parts03_button_layout.yaml'
  parts4:
    name: 'parts(jsk-original)'
    type: push
    yaml_file: 'package://robot_assembler/config/kxr_parts04_button_layout.yaml'
